matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9
script:
  - set -o pipefail
  - xcodebuild test -scheme EnumConvertible -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty -c
  - xcodebuild test -scheme EnumConvertible -configuration Debug -sdk macosx | xcpretty -c
  - xcodebuild test -scheme EnumConvertible -configuration Debug -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c
  - swift test
  - ENUM_CONVERTIBLE_MAX_SERIAL_NUMBER=8 ENUM_CONVERTIBLE_SPECIFIC_NUMBERS=10,15 xcodebuild test -scheme EnumConvertible -configuration Debug -sdk macosx | xcpretty -c
